config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'comments/create'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :sign_out
    get '/auth/:provider/callback', to: 'devise/sessions#create'
  end
  # get '/auth/:provider/callback', to: 'sessions#create'

  get 'welcome/index'

  get '/change_free', to: 'billboards#change_free', as: 'change_free'
  get '/show_booked', to: 'billboards#show_booked', as: 'show_booked'
  # post '/show_booked', to: 'billboards#show_booked', as: 'show_booked'
  get '/change_seen', to: 'requests#change_seen', as: 'change_seen'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resources :users
  # get  '/signup',  to: 'users#new'

  root 'billboards#index'

  resources :users, only: %i[index show]
  resources :billboards
  resources :billboards do
    post 'requests', to: 'requests#create'
    # post 'comments', to: 'comments#create'
    resources :comments, only: %i[create destroy]
  end
  resources :requests
  resources :requests do
    post 'rents', to: 'rents#create'
  end
  resources :rents
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :billboard

  validates :body, presence: true, alow_blank: false
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_billboard
  before_action :authenticate_user!

  def create
    @comment = @billboard.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
  end

  def destroy
    @comment = @billboard.comments.find(params[:id])
    @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :billboard_id)
  end

  def set_billboard
    @billboard = Billboard.find(params[:billboard_id])
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>" class="col-sm-12">
  <%= comment.created_at %> --- <%= comment.user.email %>
  <% if current_user && (current_user == comment.user || current_user.admin) %>
    <%= link_to t('comment.delete'), billboard_comment_path(@billboard, comment), 
        method: :delete, remote: true, style: 'floar: right' %>
    <hr />
  <% end %>
  <%= comment.body %>
  <br />
</div>

app/views/comments/create.js.erb
$('#comment_pane').prepend("<%= j render @comment %>");
$('#comment_body').val('');

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id %>').html('');