config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'comments/create'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :sign_out
    get '/auth/:provider/callback', to: 'devise/sessions#create'
  end
  # get '/auth/:provider/callback', to: 'sessions#create'

  get 'welcome/index'

  get '/change_free', to: 'billboards#change_free', as: 'change_free'
  get '/show_booked', to: 'billboards#show_booked', as: 'show_booked'
  # post '/show_booked', to: 'billboards#show_booked', as: 'show_booked'
  get '/change_seen', to: 'requests#change_seen', as: 'change_seen'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resources :users
  # get  '/signup',  to: 'users#new'

  root 'billboards#index'

  resources :users, only: %i[index show]
  resources :billboards
  resources :billboards do
    post 'requests', to: 'requests#create'
    # post 'comments', to: 'comments#create'
    resources :comments, only: %i[create destroy]
  end
  resources :requests
  resources :requests do
    post 'rents', to: 'rents#create'
  end
  resources :rents
end

app/models/request.rb
# frozen_string_literal: true

class Request < ApplicationRecord
  belongs_to :user
  belongs_to :billboard
  has_one :rent
  enum ad_type: { commercial: 0, social: 1 }, _suffix: :true

  # validates :start, :end, :brand, :description, :approved?, :user_id, :billboard_id, :ad_type, presence: true
  validate :start_date_cannot_be_in_past



  def start_date_cannot_be_in_past
    if start.present? && start < Date.today
      errors.add(start, "can't be in the past")
    end
  end

end

app/controllers/requests_controller.rb
# frozen_string_literal: true

class RequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :auth_admin, except: %i[new create]
  before_action :set_billboard, except: %i[show index edit change_seen]

  # @@show_unseen = true
  def index
    # if session[:show_free] === nil
    #     session[:show_free] = false
    #   end
    session[:show_unseen] |= false

    @requests = if session[:show_unseen]
                  Request.all.where(approved: nil)
                else
                  Request.all
                end
  end

  def show
    @request = Request.find(params[:id])
    # if @request.rent == nil
    #   @rent = Rent.new
    #   @rent.user_id = @request.user_id

    #   @request.rent = @rent
    # end
  end

  def new
    @request = Request.new
  end

  def create
    # @request = Request.new(request_params)

    # if @request.save
    #   redirect_to request_path(@request)
    # else
    #    redirect_to root_path
    # end

    @request = @billboard.requests.new(request_params)
    @request.user = current_user
    @request.rent = Rent.new
    if @request.valid?
      @request.save
      redirect_to root_path
    end
  end

  def edit
    @request = Request.find(params[:id])
    @request.rent = Rent.new if @request.rent.nil?
    @request.rent.ad_type = @request.ad_type
    @request.rent.brand = @request.brand
    @request.rent.description = @request.description
    @request.rent.start = @request.start
    @request.rent.end = @request.end
    @request.rent.user_id = @request.user_id
    @request.rent.board_id = @request.billboard_id

    @similar_requests = Request.all.where('billboard_id = ?', @request.billboard_id)
                               .where('((start BETWEEN ? and ?) OR (end BETWEEN ? and ?)) OR ((? BETWEEN start AND end) OR (? BETWEEN start AND end))', @request.start, @request.end, @request.start, @request.end, @request.start, @request.end)
    @similar_requests.each do |request|
      request.update(approved: false)
      request.save
    end

    @request.update(approved: true)
    @request.rent.save
    @request.save
  end

  def update
    # @request = Request.find(params[:id])

    # @request.save
    # @redirect_to request.path(@request)
    # @billboard = Billboard.find(params[:id])
    # @billboard.update(billboard_params)
    # redirect_to billboard_path(@billboard)
  end

  def change_seen
    session[:show_unseen] = !session[:show_unseen]
    redirect_to requests_path
  end

  private

  def request_params
    params.require(:request).permit(:brand, :description, :start, :end, :ad_type, :billboard_id)
    # user_id: current_user.id
  end

  def set_billboard
    @billboard = Billboard.find(params[:billboard_id])
  end

  def auth_admin
    redirect_to root_path if current_user.admin == false
  end

  # def set_rent_from_request(req)
  #   req.is_approved? == true
  # end
end

app/helpers/requests_helper.rb
# frozen_string_literal: true

module RequestsHelper
end

app/views/requests/_requests_form.html.erb
<div class="form-group">
  <%= form_with model: [@billboard, @request] do |f| %>
<%= f.text_field  :brand, 
                    maxlength: 50, 
                    class: 'form-control',
                    required: true, 
                    minlength: 1,
                    maxlength: 50 %>
<%= f.text_area :description, 
                  cols: 100, 
                  rows: 10,
                  required: true %>
<%= f.select(:ad_type, Request.ad_types.keys.map {|t| [t.titleize, t]}, class: "form-control" ) %>
<%= f.date_field  :start,  
                    class: 'form-control',
                    required: true %>
<%= f.date_field  :end,  
                    class: 'form-control',
                    required: true %>
<%= f.submit "Create" %>
<% end %>

</div>

<%= @request.errors.full_messages.first if @request.errors.any? %>

app/views/requests/_show_div.html.erb
<% if @requests %>
  <% @requests.reverse.each do |request| %>
	
	  <h3><%= request.brand %></h3>
	  <p><%= request.description %></p>
	  <p><%= request.ad_type %></p>
	  <p><%= request.start %></p>
	  <p><%= request.end %></p>
	  <p><%= request.approved %></p>
	  <p><%= request.user_id %></p>
	  <p><%= request.billboard_id %></p>

    <p><%= link_to t('request.show'), request_path(request.id), class: "btn btn-md btn-warning"  %></p>
	  <% if request.approved.nil? %>
	  <p><%= link_to t('request.approve'), edit_request_path(request.id), class: "btn btn-md btn-success"  %></p>
	  <% end %>
  <% end %>
<% else %>

  <%= t('request.no_unseen') %>
<% end %>

app/views/requests/edit.html.erb
<p>Rent made</p>

app/views/requests/index.html.erb
<% if session[:show_unseen] %>
  <p><%= button_to "show_all", change_seen_path, method: :get %></p>
<% else %>
  <p><%= button_to "show_unseen", change_seen_path, method: :get %></p>
<% end %>


<%= render 'show_div' %>


	

app/views/requests/show.html.erb
<h3><%= @request.brand %></h3>
	<p><%= @request.description %></p>
	<p><%= @request.ad_type %></p>
	<p><%= @request.start %></p>
	<p><%= @request.end %></p>
	<p><%= @request.approved %></p>
	<p><%= @request.user_id %></p>
	<p><%= @request.billboard_id %></p>

<% if @request.rent == nil  %>
  <%= 'no rent' %>
<% else %>
  <%= t('request.by_user')  %>
  <%= @request.user_id %> 

  <%= link_to t('request.make_rent'), edit_request_path(@request.id) %>
<% end %>