config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'comments/create'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :sign_out
    get '/auth/:provider/callback', to: 'devise/sessions#create'
  end
  # get '/auth/:provider/callback', to: 'sessions#create'

  get 'welcome/index'

  get '/change_free', to: 'billboards#change_free', as: 'change_free'
  get '/show_booked', to: 'billboards#show_booked', as: 'show_booked'
  # post '/show_booked', to: 'billboards#show_booked', as: 'show_booked'
  get '/change_seen', to: 'requests#change_seen', as: 'change_seen'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resources :users
  # get  '/signup',  to: 'users#new'

  root 'billboards#index'

  resources :users, only: %i[index show]
  resources :billboards
  resources :billboards do
    post 'requests', to: 'requests#create'
    # post 'comments', to: 'comments#create'
    resources :comments, only: %i[create destroy]
  end
  resources :requests
  resources :requests do
    post 'rents', to: 'rents#create'
  end
  resources :rents
end

app/models/billboard.rb
# frozen_string_literal: true

class Billboard < ApplicationRecord
  has_many :requests
  has_many :comments, dependent: :destroy
  belongs_to :user
  has_one_attached :image
  before_create :set_default_avatar
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  validates :city, :street, :house, :price, :user_id, :latitude, :longitude, presence: true

  def set_default_avatar
    # if !self.avatar?
    image.attach(io: File.open('app/assets/images/no.png'), filename: 'no.png', content_type: 'image/png')
    # end
  end

  def address
    [house, street, city].compact.join(', ')
  end

  def address_changed?
    city_changed? || street_changed? || house_changed?
  end
end

app/controllers/billboards_controller.rb
# frozen_string_literal: true

class BillboardsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index free change_free cookies]
  before_action :auth_admin, only: %i[new create edit update]

  def index
    session[:show_booked] = [params[:from].to_i, params[:to].to_i].max

    session[:show_free] |= false

    if session[:show_booked] != 0
      @billboards = Billboard.all.where('id IN (?)', Rent.select(:board_id).where('rents.is_active = ?', true).where('end < ?', Time.now + session[:show_booked].weeks))
    else
      if session[:show_free]
        @billboards = Billboard.all.where('id NOT IN (?)', Rent.where('start < ?', DateTime.now.beginning_of_day).where('rents.is_active = ?', true).select(:board_id))
      else
        @billboards = Billboard.all
      end
    end
  end

  def show
    @billboard = Billboard.find(params[:id])

    @request = Request.new
    @requests = @billboard.requests

    @comment = Comment.new
    @comments = @billboard.comments.order('created_at DESC')
  end

  def new
    @billboard = Billboard.new
  end

  def create
    # auth_admin
    # if current_user.admin
    @billboard = Billboard.new(billboard_params)

    if @billboard.save
      redirect_to billboard_path(@billboard)
    else
      redirect_to root_path
    end
    # else
    #  redirect_to root_path
    # end
  end

  def edit
    @billboard = Billboard.find(params[:id])
  end

  def update
    @billboard = Billboard.find(params[:id])
    @billboard.update(billboard_params)
    redirect_to billboard_path(@billboard)
  end

  def change_free
    session[:show_free] = !session[:show_free]
    redirect_to billboards_path
  end

  # def show_booked
  #   #redirect_to requests_path
  #   #session[:from] |= params[:from]
  #   x = [params[:from].to_i, params[:to].to_i].max

  #   session[:show_booked] = x
  #   redirect_to billboards_path
  #   # if max == 0
  #   #    = 0
  #   #   redirect_to billboards_path
  #   # else
  #   #   session[:show_booked] = max
  #   #   redirect_to billboards_path
  #   # end

  # end

  private

  def billboard_params
    params.require(:billboard).permit(:city,  :street, :house, :price, :image, :latitude, :longitude).merge(user_id: current_user.id)
    # user_id: current_user.id
  end
end

app/helpers/billboards_helper.rb
# frozen_string_literal: true

module BillboardsHelper
end

app/views/billboards/_bilboard.html.erb
<% @ubillboards.each do |billboard| %>
<div class="col-sm-3 single-post-card" id=<%= billboard_path(billboard.id) %>>
  <h3><%= post.street %></h3> 
  <p><%= post.price %></p>
    <%= link_to t('billboards.more'), billboard_path(billboard.id), class: 'interested' %>
</div><!-- col-sm-3 -->
<% end %>

app/views/billboards/edit.html.erb
<div class="container new-post">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1><%= t('billboards.edit.title') %></h1>
        <%= render 'billboards/new/billboards_form' %>
    </div>
  </div>
</div>

app/views/billboards/index.html.erb
<% provide :head_tags do %>
<meta name='turbolinks-visit-control' content='reload'>
    <script>

    document.addEventListener("DOMContentLoaded", function(){
    	initMap();
    });

    function initMap() {
    	var marker;
    	var newCoord;
    	var average_lat = 0;
    	var average_lng = 0;
    	var count = <%= @billboards.length %>;
    var myCoords = new google.maps.LatLng(53.9, 27.559);
    var mapOptions = {
    center: myCoords,
    zoom: 14
    };

    var billboards = <%= @billboards.to_json.html_safe %>;

    var map = new google.maps.Map(document.getElementById('map'), mapOptions);



    <% @billboards.each do |billboard| %>
    	average_lat += <%= billboard.latitude.to_json %>;
    	average_lng += <%= billboard.longitude.to_json %>;
    	newCoord = new google.maps.LatLng(<%= billboard.latitude.to_json %>, <%= billboard.longitude.to_json %>);

    	marker = new google.maps.Marker({
        position: newCoord,
        map: map
      });
    <% end %>

    myCoords = new google.maps.LatLng(average_lat/count, average_lng/count);
    map.setCenter(myCoords);
}
    </script>
<% end %>

<h1><%= t('billboards.index.results') %></h1>
<div class="container">
  <div class="row">
    <div id="map" class="col-sm-12"></div>
  </div>
  <div class="row">
    <div class="col-lg-12">
    <% if session[:show_free] === false %>
      <p><%= button_to t('index.show_free'), change_free_path, method: :get, class: "btn btn_default btn-block index" %></p>
    <% else %>
      <p><%= button_to t('index.show_all'), change_free_path, method: :get, class: "btn btn_default btn-block index" %></p>
    <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 free">
      <%= form_tag("/billboards", method: "get", class: "form-group") do %>
        <div class="col-md-4 from-control float-left">
            <%= number_field_tag(:from, nil, in: 0..25, class: "form-control") %>
        </div>
        <div class="col-md-4 from-control float-left">
            <%= number_field_tag(:to, nil, in: 0..25, class: "form-control") %>
        </div>
        <div class="col-md-4 float-left">
            <%= submit_tag(t('index.show_booked'), class: "form-control btn btn-block btn-info") %>
        </div>
        
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <% @billboards.each do |billboard| %>
        <div class="col-sm-4 float-left card" id=<%= billboard_path(billboard.id) %> style="padding: 1em;">
          <div class="card-header"><%= billboard.street %>, <%= billboard.house %></div>
          <p class="text-danger"><%= billboard.price %></p>
          <%= link_to t('billboards.more'), billboard_path(billboard.id), class: "btn btn_info" %>
          <% if current_user && current_user.admin? %>
            <%= link_to t('billboards.edit.title'), edit_billboard_path(billboard.id) %>
          <% end %>
        </div><!-- col-sm-4 -->
      <% end %>
    </div>
  </div>


  </div>
</div>

app/views/billboards/new.html.erb
<div class="container new-post">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1><%= t('billboards.new.title') %></h1>
        <%= render 'billboards/new/billboards_form' %>
    </div>
  </div>
</div>

app/views/billboards/show.html.erb
<% provide :head_tags do %>
<meta name='turbolinks-visit-control' content='reload'>
    <script>
    document.addEventListener("DOMContentLoaded", function(){
        initMap(<%=@billboard.latitude%>, <%=@billboard.longitude%>)
    });


    function initMap(lat, lng) {

    var myCoords = new google.maps.LatLng(lat, lng);

    var mapOptions = {
    center: myCoords,
    zoom: 14
    };

    var map = new google.maps.Map(document.getElementById('map'), mapOptions);

    var marker = new google.maps.Marker({
        position: myCoords,
        map: map
    });

}
    </script> 
<% end %>



<div id="single-billboard-content" class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="posted-by">Posted by <%= @billboard.user.username %></div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
        <div id="map" style="max-width: 80%"></div>
    </div>
    <div class="col-md-6">
      <%= image_tag @billboard.image, class: "img-responsive img-show" %>
    </div>
  </div>
  <div class="row">
    <table class="table table-striped show-table">
      <th><%= @billboard.city.to_s + ' ' + @billboard.street.to_s + ' ' + @billboard.house.to_s %></th>
      <th></th>
      <tr>
        <td><%= t('billboards.show.price') %></td>
        <td><%= @billboard.price %></td>
      </tr>
    </table>
  </div>
</div><!-- row -->
  <% if current_user %>
    <%= render '/requests/requests_form' %>
    <div class="row">
      <%= form_with model: [@billboard, @comment] do |f| %>
      <%= f.text_field :body %>
      <%= f.submit "Comment" %>
      <% end %>
    </div>
  <% else %>
    <%= link_to t('request.create.login'), new_user_registration_path %>
  <% end %>
  <div class="row" id="comment_pane">
    <% @comments.each do |comment| %>
      <%= render 'comments/comment', comment: comment %>
    <% end %>
  </div>

 
</div>