config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'comments/create'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :sign_out
    get '/auth/:provider/callback', to: 'devise/sessions#create'
  end
  # get '/auth/:provider/callback', to: 'sessions#create'

  get 'welcome/index'

  get '/change_free', to: 'billboards#change_free', as: 'change_free'
  get '/show_booked', to: 'billboards#show_booked', as: 'show_booked'
  # post '/show_booked', to: 'billboards#show_booked', as: 'show_booked'
  get '/change_seen', to: 'requests#change_seen', as: 'change_seen'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resources :users
  # get  '/signup',  to: 'users#new'

  root 'billboards#index'

  resources :users, only: %i[index show]
  resources :billboards
  resources :billboards do
    post 'requests', to: 'requests#create'
    # post 'comments', to: 'comments#create'
    resources :comments, only: %i[create destroy]
  end
  resources :requests
  resources :requests do
    post 'rents', to: 'rents#create'
  end
  resources :rents
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to t('header.title'), root_path, class: "navbar-brand" %>
        <% if current_user && current_user.admin %>
        <%= link_to t('nav.requests'), requests_path, class: 'btn btn-md btn-info'  %>
      <% end %>
  <div class="btn-group" role="group" aria-label="Log in / sign up">
  	<% if current_user  %>
      <%= link_to image_tag(current_user.avatar, class: "nav-img"), user_path(current_user) %>
  		<%= link_to t('user.sign_out'), destroy_user_session_path, method: :delete, class: "btn btn-md btn-secondary" %>
  	<% else %>
  	  <%= link_to t('user.sign_in'), new_user_session_path, class: "btn btn-md btn-secondary" %>
  		<%= link_to t('user.sign_up'), new_user_registration_path, class: "btn btn-md btn-secondary" %>
  	<% end %>
	</div>
  

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('index.page_title') %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyBGLCeWTZmR_4RYxDRRCMaePP458LvoC0U ' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:head_tags) %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/OverlappingMarkerSpiderfier/1.0.3/oms.min.js' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header>
      <%= render 'layouts/nav' %>
    </header>
    <div class="container">
      <%= render 'layouts/alerts' %>
      <%= yield %>
    </div>
  </body>
</html>

<!-- navbar-fixed-top navbar-inverse -->

<!--<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="#">Features</a>
      <a class="nav-item nav-link" href="#">Pricing</a>
      <a class="nav-item nav-link disabled" href="#">Disabled</a>
    </div>
  </div>
</nav>-->